// Builds db/seed.sql from the framework modules and the Ministry of Manpower open data.
// Deterministic: the same inputs always produce the same database.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const F = (p) => path.join(root, p);
const load = (m) => import(new URL(`../data/framework/${m}.mjs`, import.meta.url));

const { clusters, sectors } = await load('sectors');
const { ccsClusters, ccsBands, ccs } = await load('ccs');
const { tscLadder, categoryAccents, crossSectorTscs } = await load('tsc-core');
const { tscsA } = await load('tsc-sectors-a');
const { tscsB } = await load('tsc-sectors-b');
const { tscsC } = await load('tsc-sectors-c');
const { rolesA } = await load('roles-a');
const { rolesB } = await load('roles-b');
const { rolesC } = await load('roles-c');
const { courses, fundingSchemes } = await load('courses');

const allTscs = [...crossSectorTscs, ...tscsA, ...tscsB, ...tscsC];
const allRoles = [...rolesA, ...rolesB, ...rolesC];

// --- deterministic PRNG ----------------------------------------------------
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(20260830);
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];
const pickN = (arr, n) => { const c = [...arr]; const out = []; while (out.length < n && c.length) out.push(c.splice(Math.floor(rnd() * c.length), 1)[0]); return out; };
const int = (lo, hi) => lo + Math.floor(rnd() * (hi - lo + 1));

// --- SQL helpers -----------------------------------------------------------
const out = [];
const q = (v) => v === null || v === undefined ? 'NULL'
  : typeof v === 'number' ? String(v)
  : `'${String(v).replace(/'/g, "''")}'`;
const insert = (table, cols, rows) => {
  if (!rows.length) return;
  // D1 caps individual statement size, so batch by rendered byte length, not row count.
  const MAX = 40000;
  let buf = [], size = 0;
  const flush = () => {
    if (!buf.length) return;
    out.push(`INSERT INTO ${table} (${cols.join(', ')}) VALUES\n` + buf.join(',\n') + ';');
    buf = []; size = 0;
  };
  for (const r of rows) {
    const s = `(${r.map(q).join(', ')})`;
    if (size + s.length > MAX) flush();
    buf.push(s); size += s.length + 2;
  }
  flush();
};

out.push('-- Generated by scripts/build-seed.mjs. Do not edit by hand.');
out.push('PRAGMA foreign_keys = OFF;');

// ===========================================================================
// Registry
// ===========================================================================
insert('clusters', ['code', 'name', 'blurb'], clusters.map((c) => [c.code, c.name, c.blurb]));

const sectorId = new Map();
sectors.forEach((s, i) => sectorId.set(s.code, i + 1));
insert('sectors',
  ['id', 'code', 'name', 'cluster', 'description', 'lead_agency', 'outlook', 'mom_industry', 'published_on', 'revised_on'],
  sectors.map((s) => [sectorId.get(s.code), s.code, s.name, s.cluster, s.description, s.leadAgency, s.outlook, s.momIndustry, s.published, s.revision]));

const catId = new Map();
const cats = [...new Set(allTscs.map((t) => t.category))].sort();
cats.forEach((c, i) => catId.set(c, i + 1));
insert('tsc_categories', ['id', 'name', 'accents'],
  cats.map((c) => [catId.get(c), c, JSON.stringify(categoryAccents[c] || [])]));

const tscId = new Map();
allTscs.forEach((t, i) => tscId.set(t.code, i + 1));
insert('tscs', ['id', 'code', 'title', 'description', 'category_id', 'sector_id', 'min_level', 'max_level'],
  allTscs.map((t) => [tscId.get(t.code), t.code, t.title,
    `Covers ${t.focus}.`,
    catId.get(t.category), t.sector ? sectorId.get(t.sector) : null, t.minLevel, t.maxLevel]));

// Level descriptors: ladder template + category accent, so every TSC level reads
// specifically rather than generically.
const tscLevelRows = [];
let tlId = 1;
for (const t of allTscs) {
  const accents = categoryAccents[t.category] || [];
  for (let lv = t.minLevel; lv <= t.maxLevel; lv++) {
    const rung = tscLadder[lv - 1];
    const accent = accents[lv - 1];
    const base = rung.template.replace('{focus}', t.focus);
    const descriptor = accent ? base.replace(/\.$/, `, ${accent}.`) : base;
    tscLevelRows.push([tlId++, tscId.get(t.code), lv, rung.name, descriptor, rung.autonomy, rung.complexity]);
  }
}
insert('tsc_levels', ['id', 'tsc_id', 'level', 'level_name', 'descriptor', 'autonomy', 'complexity'], tscLevelRows);

insert('ccs_clusters', ['code', 'name', 'blurb'], ccsClusters.map((c) => [c.code, c.name, c.blurb]));
const ccsId = new Map();
ccs.forEach((c, i) => ccsId.set(c.code, i + 1));
insert('ccs', ['id', 'code', 'title', 'description', 'cluster'],
  ccs.map((c) => [ccsId.get(c.code), c.code, c.title, c.description, c.cluster]));
const ccsLevelRows = [];
let clId = 1;
for (const c of ccs) for (const l of c.levels) {
  ccsLevelRows.push([clId++, ccsId.get(c.code), l.band, ccsBands[l.band - 1].name, l.descriptor, JSON.stringify(l.behaviours)]);
}
insert('ccs_levels', ['id', 'ccs_id', 'band', 'band_name', 'descriptor', 'behaviours'], ccsLevelRows);

const roleId = new Map();
allRoles.forEach((r, i) => roleId.set(r.code, i + 1));
insert('job_roles',
  ['id', 'code', 'title', 'sector_id', 'track', 'band', 'ssoc', 'pay_p25', 'pay_median', 'pay_p75', 'demand_index', 'description'],
  allRoles.map((r) => {
    const sec = sectors.find((s) => s.code === r.sector);
    return [roleId.get(r.code), r.code, r.title, sectorId.get(r.sector), r.track, r.band, r.ssoc,
      r.payP25, r.payMedian, r.payP75, r.demand,
      `${r.band}-band role on the ${r.track} track in ${sec.name}.`];
  }));

// Role → TSC. Criticality falls out of how far the requirement sits above the TSC floor.
const bandBase = { Support: 1, Associate: 1, Professional: 2, Manager: 2, Leader: 3 };
const roleTscRows = [];
const missingTsc = new Set();
for (const r of allRoles) {
  r.tscs.forEach((spec, idx) => {
    const [code, lvl] = spec.split(':');
    if (!tscId.has(code)) { missingTsc.add(code); return; }
    // Roles list their skills most-central first, which is what criticality records.
    const criticality = idx === 0 ? 'core' : idx === 1 ? 'core' : idx === 2 ? 'important' : 'useful';
    roleTscRows.push([roleId.get(r.code), tscId.get(code), Number(lvl), criticality]);
  });
}
insert('role_tsc', ['role_id', 'tsc_id', 'required_level', 'criticality'], roleTscRows);

// Role → CCS. Every role carries all 16 CCS: the baseline band comes from seniority,
// and the role's emphasis list lifts the three or four that matter most.
const roleCcsRows = [];
for (const r of allRoles) {
  const base = bandBase[r.band];
  for (const c of ccs) {
    const emphasised = r.ccs.includes(c.code) ? 1 : 0;
    const band = Math.min(3, base + emphasised);
    roleCcsRows.push([roleId.get(r.code), ccsId.get(c.code), band, emphasised]);
  }
}
insert('role_ccs', ['role_id', 'ccs_id', 'required_band', 'emphasis'], roleCcsRows);

// Career pathways, computed from real skill overlap between roles.
const roleSkillSet = new Map();
for (const r of allRoles) {
  const m = new Map();
  for (const spec of r.tscs) { const [c, l] = spec.split(':'); if (tscId.has(c)) m.set(c, Number(l)); }
  roleSkillSet.set(r.code, m);
}
const bandOrder = ['Support', 'Associate', 'Professional', 'Manager', 'Leader'];
const clusterOf = new Map(sectors.map((x) => [x.code, x.cluster]));
const ccsBandOf = (role, code) =>
  Math.min(3, bandBase[role.band] + (role.ccs.includes(code) ? 1 : 0));

const pathRows = [];
for (const from of allRoles) {
  const fm = roleSkillSet.get(from.code);
  const bi = bandOrder.indexOf(from.band);
  const scored = [];
  for (const to of allRoles) {
    if (to.code === from.code) continue;
    const bj = bandOrder.indexOf(to.band);
    // A pathway is a step sideways or one band up. Dropping a band, or jumping two,
    // is not a transition a single move delivers.
    if (bj < bi || bj - bi > 1) continue;
    const tm = roleSkillSet.get(to.code);
    if (!tm.size) continue;

    // Technical transfer: partial credit, because a skill held one level short
    // still carries most of the way.
    let tscScore = 0, gap = 0;
    for (const [c, lvl] of tm) {
      const have = fm.get(c) ?? 0;
      if (have >= lvl) tscScore += 1;
      else { gap++; tscScore += have >= lvl - 1 ? 0.6 : have > 0 ? 0.3 : 0; }
    }
    const tscCoverage = tscScore / tm.size;

    // Core-skill transfer: this is what Critical Core Skills are for: they are the
    // part of a person that moves between sectors when the technical skills do not.
    let ccsScore = 0;
    for (const c of ccs) {
      const need = ccsBandOf(to, c.code);
      const have = ccsBandOf(from, c.code);
      ccsScore += have >= need ? 1 : have === need - 1 ? 0.5 : 0;
    }
    const ccsCoverage = ccsScore / ccs.length;

    const overlap = Math.round((0.7 * tscCoverage + 0.3 * ccsCoverage) * 100);
    if (overlap < 35) continue;

    const sameSector = from.sector === to.sector;
    const sameCluster = clusterOf.get(from.sector) === clusterOf.get(to.sector);
    const kind = !sameSector ? 'cross-sector' : bj > bi ? 'vertical' : 'lateral';
    // Ranking prefers moves that stay near existing context; the stored overlap is
    // the honest transfer figure either way.
    const rank = overlap + (sameSector ? 20 : sameCluster ? 7 : 0) + (bj === bi ? 4 : 0);
    scored.push({ to, overlap, gap, kind, rank });
  }
  scored.sort((a, b) => b.rank - a.rank || a.gap - b.gap);
  for (const s2 of scored.slice(0, 8)) {
    pathRows.push([roleId.get(from.code), roleId.get(s2.to.code), s2.kind, s2.overlap, s2.gap]);
  }
}
insert('role_pathways', ['from_role_id', 'to_role_id', 'kind', 'overlap_pct', 'gap_count'], pathRows);

const courseId = new Map();
courses.forEach((c, i) => courseId.set(c.code, i + 1));
insert('courses', ['id', 'code', 'title', 'provider', 'mode', 'hours', 'qual_level', 'full_fee', 'outcome', 'provenance'],
  courses.map((c) => [courseId.get(c.code), c.code, c.title, c.provider, c.mode, c.hours, c.qual, c.fee, c.outcome, c.provenance]));

const courseSkillRows = [];
const missingSkill = new Set();
for (const c of courses) {
  for (const spec of c.skills) {
    const [code, lvl] = spec.split(':');
    if (tscId.has(code)) courseSkillRows.push([courseId.get(c.code), 'tsc', tscId.get(code), Number(lvl)]);
    else if (ccsId.has(code)) courseSkillRows.push([courseId.get(c.code), 'ccs', ccsId.get(code), Number(lvl)]);
    else missingSkill.add(code);
  }
}
insert('course_skills', ['course_id', 'skill_type', 'skill_id', 'level'], courseSkillRows);

insert('funding_schemes', ['code', 'name', 'kind', 'amount', 'rate', 'eligibility', 'note'],
  fundingSchemes.map((s) => [s.code, s.name, s.kind, s.amount ?? null, s.rate ?? null, s.eligibility, s.note]));

fs.writeFileSync(F('db/seed.sql'), out.join('\n\n') + '\n');
console.log('registry written');
console.log('  sectors', sectors.length, '| TSCs', allTscs.length, '| TSC levels', tscLevelRows.length);
console.log('  CCS', ccs.length, '| CCS levels', ccsLevelRows.length);
console.log('  roles', allRoles.length, '| role-TSC', roleTscRows.length, '| role-CCS', roleCcsRows.length);
console.log('  pathways', pathRows.length, '| courses', courses.length, '| course-skills', courseSkillRows.length);
if (missingTsc.size) console.warn('  !! unknown TSC codes in roles:', [...missingTsc].join(', '));
if (missingSkill.size) console.warn('  !! unknown skill codes in courses:', [...missingSkill].join(', '));

// Export lookup maps for the second stage of the build.
fs.writeFileSync(F('db/.ids.json'), JSON.stringify({
  sector: Object.fromEntries(sectorId), tsc: Object.fromEntries(tscId),
  ccs: Object.fromEntries(ccsId), role: Object.fromEntries(roleId),
  course: Object.fromEntries(courseId),
}));
